version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control
    outputs:
      highly_sensitive:
        cohort: output/input_control.csv
        
  generate_study_population_treatment:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treatment
    outputs:
      highly_sensitive:
        cohort: output/input_treatment.csv
  
  generate_study_population_treatment_sensitivity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treatment_sensitivity
    outputs:
      highly_sensitive:
        cohort: output/input_treatment_sensitivity.csv

  data_properties:
    run: r:latest analysis/data_properties.R output/input_control.csv output/input_treatment.csv output/input_treatment_sensitivity.csv output/data_properties
    needs: [generate_study_population_control, generate_study_population_treatment, generate_study_population_treatment_sensitivity]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/input*.txt

  define_covariates_combine:
    run: stata-mp:latest analysis/004_define_covariates_combine.do
    needs: [generate_study_population_control, generate_study_population_treatment, generate_study_population_treatment_sensitivity]
    outputs:
      moderately_sensitive:
        log: logs/cleaning_dataset_combine.log 
      highly_sensitive:
        data: output/data/main.dta
        data1: output/data/sensitivity_analysis.dta

  baseline_characteristic:
    run: stata-mp:latest analysis/101_baseline_characteristics.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/baseline_characterisitcs.log 
        data: output/tables/baseline_allpts.csv  
        data1: output/tables/baseline_allpts_sensitivity.csv  

  cox_model:
    run: stata-mp:latest analysis/204_cox_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/cox_model.log 
        data: output/tables/cox_model_summary.csv 
        data1: output/tables/cox_model_disease.csv 
        data2: output/tables/cox_model_rates.csv 
        data3: output/tables/cox_model_rates_round.csv 
        data4: output/tablescox_model_summary_sens_1.csv 
        data5: output/tables/cox_model_disease_sens_1.csv 
        data6: output/tables/cox_model_rates_sens_1.csv 
        data7: output/tables/cox_model_rates_round_sens_1.csv 
        data8: output/tables/cox_model_rates_round_sens_2.csv 
        data9: output/tablescox_model_summary_sens_4.csv 
        data10: output/tables/cox_model_rates_sens_4.csv 
        data11: output/tables/cox_model_rates_round_sens_4.csv 
        data12: output/tablescox_model_summary_sens_5.csv 
        data13: output/tables/cox_model_rates_sens_5.csv 
        data14: output/tables/cox_model_rates_round_sens_5.csv 
        data15: output/tablescox_model_summary_sens_6.csv 
        data16: output/tables/cox_model_rates_sens_6.csv 
        data17: output/tables/cox_model_rates_round_sens_6.csv 
        schoenfield_ae_all: output/figures/schoenfield_ae_all.svg
        schoenfield_ae_all_serious: output/figures/schoenfield_ae_all_serious.svg
        schoenfield_ae_spc_all: output/figures/schoenfield_ae_spc_all.svg
        schoenfield_ae_spc_serious: output/figures/schoenfield_ae_spc_serious.svg
        schoenfield_ae_drug_all: output/figures/schoenfield_ae_drug_all.svg
        schoenfield_ae_drug_serious: output/figures/schoenfield_ae_drug_serious.svg
        schoenfield_ae_imae_all: output/figures/schoenfield_ae_imae_all.svg
        schoenfield_ae_imae_serious: output/figures/schoenfield_ae_imae_serious.svg
        loglog_plot_ae_all: output/figures/loglog_plot_ae_all.svg
        loglog_plot_ae_all_serious: output/figures/loglog_plot_ae_all_serious.svg
        loglog_plot_ae_spc_all: output/figures/loglog_plot_ae_spc_all.svg
        loglog_plot_ae_spc_serious: output/figures/loglog_plot_ae_spc_serious.svg
        loglog_plot_ae_drug_all: output/figures/loglog_plot_ae_drug_all.svg
        loglog_plot_ae_drug_serious: output/figures/loglog_plot_ae_drug_serious.svg
        loglog_plot_ae_imae_all: output/figures/loglog_plot_ae_imae_all.svg
        loglog_plot_ae_imae_serious: output/figures/loglog_plot_ae_imae_serious.svg

  PS_model:
    run: stata-mp:latest analysis/304_ps_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/ps_model.log
        data: output/tables/cox_propensity.csv 
        histogram_agesex: output/figures/histogram_agesex.svg
        histogram_adj: output/figures/histogram_adj.svg
        histogram_adj2: output/figures/histogram_adj2.svg
        histogram_adj3: output/figures/histogram_adj3.svg
        histogram_adj4: output/figures/histogram_adj4.svg
        balance_agesex: output/figures/balance_agesex.svg
        balance_adj: output/figures/balance_adj.svg
        balance_adj2: output/figures/balance_adj2.svg
        balance_adj3: output/figures/balance_adj3.svg
        balance_adj4: output/figures/balance_adj4.svg
        
  preceed_rate:
    run: stata-mp:latest analysis/405_preceeding_rate.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/preceed_rate.log 
        data: output/tables/comparator_rates.csv 
        data1: output/tables/comparator_rates_round.csv 
  
  redacted_table:
    run: stata-mp:latest analysis/501_redacted_table.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log1: logs/redacted_table.log   
        data: output/tables/baseline_table_redact_bydrug.csv   
        data1: output/tables/baseline_table_redact_mean.csv
        data2: output/tables/baseline_table_redact_bydrug_sens.csv   
        data3: output/tables/baseline_table_redact_mean_sens.csv

