version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control
    outputs:
      highly_sensitive:
        cohort: output/input_control.csv
        
  generate_study_population_treatment:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treatment
    outputs:
      highly_sensitive:
        cohort: output/input_treatment.csv

  data_properties:
    run: r:latest analysis/data_properties.R output/input_control.csv output
    needs: [generate_study_population_control]
    outputs:
      moderately_sensitive:
        cohort: output/input*.txt

  define_covariates_combine:
    run: stata-mp:latest analysis/001_define_covariates_combine.do
    needs: [generate_study_population_control, generate_study_population_treatment]
    outputs:
      moderately_sensitive:
        log: logs/cleaning_dataset_combine.log 
      highly_sensitive:
        data: output/data/main.dta

  baseline_characteristic:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/baseline_characterisitcs.log 


  cox_model:
    run: stata-mp:latest analysis/200_cox_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/cox_model.log 
        data: output/tables/cox_model_summary.dta
        survrisk_ae_all: output/figures/survrisk_ae_all.svg
        survrisk_ae_spc_all: output/figures/survrisk_ae_spc_all.svg
        survrisk_ae_drug_all: output/figures/survrisk_ae_drug_all.svg
        survrisk_ae_imae_all: output/figures/survrisk_ae_imae_all.svg
        survrisk_allcause_emerg_aande: output/figures/survrisk_allcause_emerg_aande.svg
        survrisk_covid_hosp_date: output/figures/survrisk_covid_hosp_date.svg
        survrisk_all_hosp_date: output/figures/survrisk_all_hosp_date.svg
        survrisk_died_date_ons: output/figures/survrisk_died_date_ons.svg
        survhaz_ae_all: output/figures/survhaz_ae_all.svg
        survhaz_ae_spc_all: output/figures/survhaz_ae_spc_all.svg
        survhaz_ae_drug_all: output/figures/survhaz_ae_drug_all.svg
        survhaz_ae_imae_all: output/figures/survhaz_ae_imae_all.svg
        survhaz_allcause_emerg_aande: output/figures/survhaz_allcause_emerg_aande.svg
        survhaz_covid_hosp_date: output/figures/survhaz_covid_hosp_date.svg
        survhaz_all_hosp_date: output/figures/survhaz_all_hosp_date.svg
        survhaz_died_date_ons: output/figures/survhaz_died_date_ons.svg 
        survcur_ae_all: output/figures/survcur_ae_all.svg
        survcur_ae_spc_all: output/figures/survcur_ae_spc_all.svg
        survcur_ae_drug_all: output/figures/survcur_ae_drug_all.svg
        survcur_ae_imae_all: output/figures/survcur_ae_imae_all.svg
        survcur_allcause_emerg_aande: output/figures/survcur_allcause_emerg_aande.svg
        survcur_covid_hosp_date: output/figures/survcur_covid_hosp_date.svg
        survcur_all_hosp_date: output/figures/survcur_all_hosp_date.svg
        survcur_died_date_ons: output/figures/survcur_died_date_ons.svg

  PS_model:
    run: stata-mp:latest analysis/300_ps_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/ps_model.log
        data: output/tables/cox_model_propensity.dta
        histogram_agesex: output/figures/histogram_agesex.svg
        histogram_adj: output/figures/histogram_adj.svg
        histogram_fuladj1: output/figures/histogram_fulladj1.svg
        histogram_fulladj2: output/figures/histogram_fulladj2.svg
        match_agesex: output/figures/match_agesex.svg
        match_adj: output/figures/match_adj.svg
        match_fulladj1: output/figures/match_fulladj1.svg
        match_fulladj2: output/figures/match_fulladj2.svg  
  
  preceed_rate:
    run: stata-mp:latest analysis/400_preceeding_rate.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/preceed_rate.log 
        data: output/tables/comparator_rate_summary.dta