version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_control
    outputs:
      highly_sensitive:
        cohort: output/input_control.csv
        
  generate_study_population_treatment:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_treatment
    outputs:
      highly_sensitive:
        cohort: output/input_treatment.csv

  data_properties:
    run: r:latest analysis/data_properties.R output/input_control.csv output/input_treatment.csv output/data_properties
    needs: [generate_study_population_control, generate_study_population_treatment]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/input*.txt

  define_covariates_combine:
    run: stata-mp:latest analysis/003_define_covariates_combine.do
    needs: [generate_study_population_control, generate_study_population_treatment]
    outputs:
      moderately_sensitive:
        log: logs/cleaning_dataset_combine.log 
      highly_sensitive:
        data: output/data/main.dta

  baseline_characteristic:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/baseline_characterisitcs.log 
        data: output/tables/baseline_allpts.csv      

  cox_model:
    run: stata-mp:latest analysis/201_cox_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/cox_model.log 
        data: output/tables/cox_model_summary.csv 
        data1: output/tables/cox_model_disease.csv 
        data2: output/tables/cox_model_rates.csv 
        survrisk_ae_spc_all: output/figures/survrisk_ae_spc_all.svg
        survrisk_ae_drug_all: output/figures/survrisk_ae_drug_all.svg
        survrisk_ae_imae_all: output/figures/survrisk_ae_imae_all.svg
        survrisk_ae_all: output/figures/survrisk_ae_all.svg
        survrisk_allcause_emerg_aande: output/figures/survrisk_allcause_emerg_aande.svg
        survrisk_covid_hosp_date: output/figures/survrisk_covid_hosp_date.svg
        survrisk_all_hosp_date: output/figures/survrisk_all_hosp_date.svg
        survrisk_died_date_ons: output/figures/survrisk_died_date_ons.svg
        survrisk_ae_diverticulitis: output/figures/survrisk_ae_diverticulitis.svg
        survrisk_ae_diarrhoea: output/figures/survrisk_ae_diarrhoea.svg
        survrisk_ae_taste: output/figures/survrisk_ae_taste.svg
        survrisk_ae_rash: output/figures/survrisk_ae_rash.svg
        survrisk_ae_bronchospasm: output/figures/survrisk_ae_bronchospasm.svg
        survrisk_ae_contactderm: output/figures/survrisk_ae_contactderm.svg
        survrisk_ae_dizziness: output/figures/survrisk_ae_dizziness.svg
        survrisk_ae_nausea_vomit: output/figures/survrisk_ae_nausea_vomit.svg
        survrisk_ae_headache: output/figures/survrisk_ae_headache.svg
        survrisk_ae_anaphylaxis: output/figures/survrisk_ae_anaphylaxis.svg
        survrisk_ae_severe_drug: output/figures/survrisk_ae_severe_drug.svg
        survrisk_ae_nonsevere_drug: output/figures/survrisk_ae_nonsevere_drug.svg
        survrisk_ae_ra: output/figures/survrisk_ae_ra.svg
        survrisk_ae_sle: output/figures/survrisk_ae_sle.svg
        survrisk_ae_psorasis: output/figures/survrisk_ae_psorasis.svg
        survrisk_ae_psa: output/figures/survrisk_ae_psa.svg
        survrisk_ae_axspa: output/figures/survrisk_ae_axspa.svg
        survrisk_ae_ibd: output/figures/survrisk_ae_ibd.svg
        survcur_ae_spc_all: output/figures/survcur_ae_spc_all.svg
        survcur_ae_drug_all: output/figures/survcur_ae_drug_all.svg
        survcur_ae_imae_all: output/figures/survcur_ae_imae_all.svg
        survcur_ae_all: output/figures/survcur_ae_all.svg
        survcur_allcause_emerg_aande: output/figures/survcur_allcause_emerg_aande.svg
        survcur_covid_hosp_date: output/figures/survcur_covid_hosp_date.svg
        survcur_all_hosp_date: output/figures/survcur_all_hosp_date.svg
        survcur_died_date_ons: output/figures/survcur_died_date_ons.svg
        survcur_ae_diverticulitis: output/figures/survcur_ae_diverticulitis.svg
        survcur_ae_diarrhoea: output/figures/survcur_ae_diarrhoea.svg
        survcur_ae_taste: output/figures/survcur_ae_taste.svg
        survcur_ae_rash: output/figures/survcur_ae_rash.svg
        survcur_ae_bronchospasm: output/figures/survcur_ae_bronchospasm.svg
        survcur_ae_contactderm: output/figures/survcur_ae_contactderm.svg
        survcur_ae_dizziness: output/figures/survcur_ae_dizziness.svg
        survcur_ae_nausea_vomit: output/figures/survcur_ae_nausea_vomit.svg
        survcur_ae_headache: output/figures/survcur_ae_headache.svg
        survcur_ae_anaphylaxis: output/figures/survcur_ae_anaphylaxis.svg
        survcur_ae_severe_drug: output/figures/survcur_ae_severe_drug.svg
        survcur_ae_nonsevere_drug: output/figures/survcur_ae_nonsevere_drug.svg
        survcur_ae_ra: output/figures/survcur_ae_ra.svg
        survcur_ae_sle: output/figures/survcur_ae_sle.svg
        survcur_ae_psorasis: output/figures/survcur_ae_psorasis.svg
        survcur_ae_psa: output/figures/survcur_ae_psa.svg
        survcur_ae_axspa: output/figures/survcur_ae_axspa.svg
        survcur_ae_ibd: output/figures/survcur_ae_ibd.svg
        
  PS_model:
    run: stata-mp:latest analysis/301_ps_model.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/ps_model.log
        data: output/tables/cox_propensity.csv 
        histogram_agesex: output/figures/histogram_agesex.svg
        histogram_adj: output/figures/histogram_adj*.svg
        histogram_adj2: output/figures/histogram_fulladj1*.svg
        histogram_adj3: output/figures/histogram_fulladj2*.svg
        match_drug1: output/figures/match_fulladj2_drug1*.svg
        match_drug2: output/figures/match_fulladj2_drug2*.svg
        match_drug3: output/figures/match_fulladj2_drug3*.svg
        data2: output/tables/cox_propensity_common.csv 
        
  preceed_rate:
    run: stata-mp:latest analysis/400_preceeding_rate.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log: logs/preceed_rate.log 
        data: output/tables/comparator_rates.csv 
  
  redacted_table:
    run: stata-mp:latest analysis/500_redacted_table.do
    needs: [define_covariates_combine]
    outputs:
      moderately_sensitive:
        log1: logs/redacted_table.log   
        data: output/tables/baseline_table_redact_bydrug.csv   
        data1: output/tables/baseline_table_redact_mean.csv


